import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from 'next/font/google'
import Header from "./component/header/websiteHeader";
import TopHeader from "./component/header/topHeader";
import Footer from "./component/footer";

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
  variable: '--font-nunito',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={nunito.variable}>
      <body className="antialiased">
         <div className="relative z-50 bg-[var(--primary-100)] w-full">
          <TopHeader />
        </div>
        <div className="sticky top-0 z-40 bg-white">
          <Header />
        </div>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
